version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mi-clave-secreta
      - DB_NAME=db_parte1
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "33067:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mi-clave-secreta
      - MYSQL_DATABASE=db_parte1
    volumes:
      - db_data_p1:/var/lib/mysql

volumes:
  db_data_p1: